// GET ALL PROPERTIES
export const GET_ALL_PROPERTIES_REQUEST = 'GET_ALL_PROPERTIES_REQUEST';
export const GET_ALL_PROPERTIES_SUCCESS = 'GET_ALL_PROPERTIES_SUCCESS';
export const GET_ALL_PROPERTIES_FAIL = 'GET_ALL_PROPERTIES_FAIL';

// Get property detail
export const GET_PROPERRTY_DETAIL_REQUEST = 'GET_PROPERRTY_DETAIL_REQUEST';
export const GET_PROPERRTY_DETAIL_SUCCESS = 'GET_PROPERRTY_DETAIL_SUCCESS';
export const GET_PROPERRTY_DETAIL_FAIL = 'GET_PROPERRTY_DETAIL_FAIL';
