// GET ALL PROPERTIES
export const GET_ALL_PROPERTIES_REQUEST = 'GET_ALL_PROPERTIES_REQUEST';
export const GET_ALL_PROPERTIES_SUCCESS = 'GET_ALL_PROPERTIES_SUCCESS';
export const GET_ALL_PROPERTIES_FAIL = 'GET_ALL_PROPERTIES_FAIL';
