export const GET_FOR_SALE_PROPERTIES = "GET_FOR_SALE_PROPERTIES";
export const GET_FOR_RENT_PROPERTIES = "GET_FOR_RENT_PROPERTIES";
export const GET_FOR_SOLD_PROPERTIES = "GET_FOR_SOLD_PROPERTIES";
export const GET_PROPERTY = "GET_PROPERTY";
export const ERROR = "ERROR";
export const GET_USA_STATES = "GET_USA_STATES";
